-- SQL script to create RetailerDB and basic tables. Run in SQL Server / LocalDB.
IF DB_ID('RetailerDB') IS NULL
BEGIN
    CREATE DATABASE RetailerDB;
END
GO

USE RetailerDB;
GO

CREATE TABLE ItemCategory (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL);
CREATE TABLE ItemGroup (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL);
CREATE TABLE ItemSubGroup (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, GroupId INT NULL);
CREATE TABLE ItemType (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL);
CREATE TABLE UnitOfMeasure (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL);

CREATE TABLE Item (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(250) NOT NULL,
    Barcode NVARCHAR(100) NULL,
    Rate DECIMAL(18,2) NOT NULL,
    Cost DECIMAL(18,2) NOT NULL,
    CategoryId INT NOT NULL,
    ItemTypeId INT NOT NULL,
    GroupId INT NOT NULL,
    SubGroupId INT NULL,
    UnitName NVARCHAR(100) NULL,
    UnitCode NVARCHAR(50) NULL,
    UnitOfMeasureId INT NULL
);

CREATE TABLE Branches (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, Address NVARCHAR(500), ContactPerson NVARCHAR(200), MobileNo NVARCHAR(50), BillHeading1 NVARCHAR(200), BillHeading2 NVARCHAR(200), BillMobileNo NVARCHAR(50));
CREATE TABLE Employees (Id INT IDENTITY(1,1) PRIMARY KEY, FirstName NVARCHAR(200) NOT NULL, LastName NVARCHAR(200), City NVARCHAR(100), Province NVARCHAR(100), Address NVARCHAR(500), Mobile1 NVARCHAR(50), Mobile2 NVARCHAR(50), CNIC NVARCHAR(50));
CREATE TABLE Logins (Id INT IDENTITY(1,1) PRIMARY KEY, Username NVARCHAR(200) NOT NULL, PasswordHash NVARCHAR(500) NOT NULL, BranchCode NVARCHAR(50), EmployeeId INT NULL, IsActive BIT NOT NULL DEFAULT 1);

CREATE TABLE Vendor (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(250) NOT NULL, CNIC NVARCHAR(50), NTN NVARCHAR(50), Mobile NVARCHAR(50), Address NVARCHAR(500), City NVARCHAR(100), Province NVARCHAR(100));
CREATE TABLE Customer (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(250) NOT NULL, CNIC NVARCHAR(50), NTN NVARCHAR(50), Mobile NVARCHAR(50), Address NVARCHAR(500), City NVARCHAR(100), Province NVARCHAR(100));

CREATE TABLE PurchaseMaster (Id INT IDENTITY(1,1) PRIMARY KEY, Date DATETIME2, CreateDate DATETIME2, SupplierID INT, SubTotal DECIMAL(18,2), Discount DECIMAL(18,2), TaxAmount DECIMAL(18,2), Total DECIMAL(18,2), LoginId INT, BranchId INT);
CREATE TABLE PurchaseDetail (Id INT IDENTITY(1,1) PRIMARY KEY, PurchaseId INT, ItemId INT, ItemName NVARCHAR(250), Rate DECIMAL(18,2), Qty DECIMAL(18,2), Discount DECIMAL(18,2), TaxPercentage DECIMAL(18,2));

CREATE TABLE StockTransfer (Id INT IDENTITY(1,1) PRIMARY KEY, Date DATETIME2, CreateDate DATETIME2, LoginCode NVARCHAR(100), FromBranchCode NVARCHAR(100), ToBranchCode NVARCHAR(100), LoginId INT);
CREATE TABLE StockTransferDetail (Id INT IDENTITY(1,1) PRIMARY KEY, StockTransferId INT, ItemCode NVARCHAR(100), Qty DECIMAL(18,2));

CREATE TABLE SalesMaster (Id INT IDENTITY(1,1) PRIMARY KEY, Date DATETIME2, CreateDate DATETIME2, LoginId INT, BranchId INT, CustomerName NVARCHAR(250), SubTotal DECIMAL(18,2), TotalDiscount DECIMAL(18,2), TaxAmount DECIMAL(18,2), BalanceAmount DECIMAL(18,2), CustomerCode NVARCHAR(100));
CREATE TABLE SalesDetail (Id INT IDENTITY(1,1) PRIMARY KEY, SalesMasterId INT, ItemCode NVARCHAR(100), ItemName NVARCHAR(250), Rate DECIMAL(18,2), Qty DECIMAL(18,2), Discount DECIMAL(18,2), TaxPercentage DECIMAL(18,2), TaxAmount DECIMAL(18,2), Amount DECIMAL(18,2));

-- Seed a demo login: username 'admin' password 'Password123!'
INSERT INTO Logins (Username, PasswordHash, IsActive)
VALUES ('admin', 'a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea', 1);

GO
